services:

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"

  api:
    build:
      context: ../api
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-sagdu}
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: sagdu
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB:-sagdu}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
  