import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import './globals.css';
import Link from 'next/link';
import { ReactNode } from 'react';
import { SiteHeader } from '@/components/site-header';
import QueryProvider from '@/components/query-provider';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <QueryProvider>
          {/* Mobile Top Bar */}
          <header className="sticky top-0 z-40 border-b bg-background">
            <SiteHeader />
          </header>

          {/* Page content */}
          <main className="mx-auto w-full max-w-screen-sm px-3 py-4">
            {children}
          </main>

          {/* (Optional) Bottom bar — mobile tabbar */}
          {/* Remove if you don't want it */}
          <nav
            className="sticky inset-x-0 bottom-0 z-40 border-t bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60"
            style={{ paddingBottom: 'env(safe-area-inset-bottom)' }}
          >
            <div className="mx-auto grid max-w-screen-sm grid-cols-3">
              <Link
                href="/"
                className="flex items-center justify-center py-3 text-sm"
              >
                Home
              </Link>
              <Link
                href="/users"
                className="flex items-center justify-center py-3 text-sm"
              >
                Users
              </Link>
              <Link
                href="/settings"
                className="flex items-center justify-center py-3 text-sm"
              >
                Settings
              </Link>
            </div>
          </nav>
        </QueryProvider>
      </body>
    </html>
  );
}
