name: Build & Push (latest)

on:
  push: {}  # run on every push; push to registry only on default branch

permissions:
  contents: read
  packages: write  # required for GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: nicololuescher/sagdu/api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: ${{ github.ref_name == github.event.repository.default_branch }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
